### ISSUE TITLE
Add Build Instructions

### ISSUE THREAD

**Issue by firesurfer** [Celtoys/clReflect#1]
I tried building the clReflect tools on linux (Debian Testing) and failed.
Would you mind to provide some build instruction?

**Comment by dwilliamson** [comment]
The Linux build currently has no maintainer so will likely not build out of the box. You should ideally use cmake.

First generate Clang cmake files with https://github.com/Celtoys/clReflect/blob/master/extern/build-gnu.sh and build.

Then generate the clReflect cmake files and build. There is no equivalent bash script but there is one for OSX that you can copy https://github.com/Celtoys/clReflect/blob/master/build-osx.sh
