### ISSUE TITLE
exported files's data layout work only in x86

### ISSUE THREAD

**Issue by SungJJinKang** [Celtoys/clReflect#2]
When Read cppbin file in x86, It works well.
But in x64, it doesn't work

It looks output data file's data layout follow x86.
On the other hand, it looks clscan compile sourcefiles as x64. ( compiler say pointer size 8byte )

I think problem is clscan's output data layout follow x86

**Comment by SungJJinKang** [comment]
It looks clExporter consider pointer size 4byte.

**Comment by SungJJinKang** [comment]
I tried build in x64, But i couldn't.. Because it have __asm codes.

**Comment by dwilliamson** [comment]
Thanks for reporting these but I currently have no plans to work further on the 64-bit version.

If you would like to fix these issues yourself then feel free to leave the issue open.
