### ISSUE TITLE
clscan crash when it called from multiple threads

### ISSUE THREAD

**Issue by SungJJinKang** [Celtoys/clReflect#5]
```
static llvm::cl::opt<bool> Timing("timing", llvm::cl::desc("Print some rough timing info"), ToolCategory);

// Parse command-line options
auto options_parser = clang::tooling::CommonOptionsParser::create(argc, argv, ToolCategoryOption, llvm::cl::OneOrMore);
if (!options_parser)
{
  return 1;
}

// Initialize inline ASM parsing
llvm::InitializeNativeTarget();
```

if clscan is called from multiple threads, it crash.              
Because "CommonOptionsParser" shouldn't be called from multiple threads.         
This is show why it crash ( https://reviews.llvm.org/D105461 ).           

llvm still doesn't solve this problem.

I don't know how to deal with this....

**Comment by dwilliamson** [comment]
How are you calling this from multiple threads if this source is in `main`?

**Comment by SungJJinKang** [comment]
i load this library to my program as dll.
I edited some codes to export some function.

**Comment by dwilliamson** [comment]
Sorry, this is beyond the scope of this project. If you want to do this then I'd suggest pulling parameter parsing out into your own program and doing it there, before you launch multiple threads.
